### PR TITLE
person: add Krystalia to people/ directory and update peoplelist.json

### PR DESCRIPTION
**Pull request by mauvehed**
The file `krystalia.json` is added to the `people` directory. It contains information about Krystalia, including her first name, handle, obituary, and other details. The `peoplelist.json` file is also updated to include Krystalia in the list of people, with the filename `krystalia`. This allows Krystalia to be displayed in the list of people on the website.

### CODE REVIEW

**Comment by attritionorg** [comment]
`<html>
<body>


 
--
<h1 id="main-title">RestInCode - <span id="subtitle">In Memory of </span></h1>
  | </header>
  |  
  |  
  | <div id="memorial-page">
  | <div>
  | <h2 id="memorial-name"></h2>
  |  
  | <aside>
  | 
  | <p class="birth"><b>Born:</b> </p>
  | <p class="death"><b>Died:</b> </p>
  | <p class="affiliations"><b>Affiliations:</b><br></p>
  | <p class="obituary"></p>
  | 
  | <div id="social-media">
  | <h4>Social Media</h4>
  |  
  | </div>
  | </aside>
  |  
  | <p id="memorial-text">memorial image
  | </p>
  |  
  | <hr />
  | <h3>Contributions</h3>
  | <ul id="contributions-list">
  |  
  | </ul>
  |  
  | <hr />
  | <h3>Gallery</h3>
  | <div id="nogallery">
  | <div id="gallery">
  | </div>
  |  
  | </div>
  |  


</body>
</html><h1 id="main-title">RestInCode - <span id="subtitle">In Memory of </span></h1>
		</header>


		<div id="memorial-page">
			<div>
				<h2 id="memorial-name"></h2>

				<aside>
					
					<p class="birth"><b>Born:</b> </p>
					<p class="death"><b>Died:</b> </p>
					<p class="affiliations"><b>Affiliations:</b><br></p>
					<p class="obituary"></p>
					
					<div id="social-media">
					<h4>Social Media</h4>

					</div>
				</aside>

				<p id="memorial-text">memorial image
				</p>

				<hr />
				<h3>Contributions</h3>
				<ul id="contributions-list">

				</ul>

				<hr />
				<h3>Gallery</h3>
				<div id="nogallery">
				<div id="gallery">
				</div>

			</div>`

That's what "renders", obviously no real detail. So something being included is causing it not to display presumably. Odd high-bit ascii or some other character blocking it?

**Comment by mauvehed** [comment]
Yeah, I don't know. That's why I tried renaming the file, lowercasing it, etc.

**Comment by attritionorg** [comment]
I meant the content in the file

**Comment by mauvehed** [comment]
Resolved in PR #220

**Pull request closed without merging**
